name: test-foundry-stable

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  MAINNET_RPC_URL: https://eth-mainnet.g.alchemy.com/v2/${{ secrets.ALCHEMY_KEY }}

jobs:
  test_foundry_os:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            foundry: stable

          - os: macos-latest
            foundry: stable

          # - os: windows-latest
          #   foundry: stable

      fail-fast: false # ensure all jobs run even if one fails

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Check Environment
        shell: bash
        run: |
          echo "runner.os=${{ runner.os }}"
          python3 -c "import platform; info = f'{platform.system()} {platform.release()} {platform.version()} {platform.machine()}'; print('-' * len(info)); print(info); print('-' * len(info))"
          bash --version

      - name: Install Bash 5.2 (on macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          brew install bash
          bash --version

      - name: Install uv python framework
        shell: bash
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | bash
        id: uv-install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          foundry: ${{ matrix.foundry }}
        id: foundry-install

      - shell: bash
        run: |
          # foundry version
          forge --version

      - name: Install python project dependencies (if any)
        shell: bash
        run: |
          # install python project dependencies
          cd ${{ inputs.cwd }}
          [[ -f pyproject.toml ]] && uv sync || echo "No pyproject.toml found, skipping python dependencies installation"

      - name: Install node project dependencies
        shell: bash
        run: |
          # install node project dependencies
          cd ${{ inputs.cwd }}
          yarn

      - name: Run Prettier
        shell: bash
        run: |
          # run prettier to check formatting
          cd ${{ inputs.cwd }}
          yarn prettier --check
        id: prettier

      - name: Run Solhint
        shell: bash
        run: |
          # run solhint
          cd ${{ inputs.cwd }}
          yarn lint
        id: lint

      - name: Run Slither
        shell: bash
        run: |
          # run slither
          cd ${{ inputs.cwd }}
          yarn slither
        id: slither

      - name: Run Forge build, generating contract sizes reports into the regression folder - if they differ from the ones in the repo, they will be failed in the git-diffs step
        if: runner.os != 'Windows' # TODO: for some reason, the sizes processing doesn't work on windows
        shell: bash
        run: |
          # generate contract sizes reports into the regression folder - if they differ from the ones in the repo, they will be failed in the git-diffs step
          cd ${{ inputs.cwd }}
          uv run yarn sizes
        id: sizes

      - name: Run Forge tests
        shell: bash
        run: |
          # run all the foundry tests in the test folder
          cd ${{ inputs.cwd }}
          uv run yarn test
        id: test

      - name: Run Lint on Forge tests
        shell: bash
        run: |
          # run all the foundry tests in the test folder
          cd ${{ inputs.cwd }}
          uv run yarn lint:test
        id: lint-test

      - name: Run Forge tests - coverage
        if: runner.os != 'Windows' # TODO: for some reason, the coverage processing doesn't work on windows
        shell: bash
        run: |
          # generate coverage reports into the regression folder - if they differ from the ones in the repo, they will be failed in the git-diffs step
          cd ${{ inputs.cwd }}
          uv run yarn coverage
        id: coverage

      - name: Run Forge tests - gas
        if: runner.os != 'Windows' # TODO: for some reason, the gas processing doesn't work on windows
        shell: bash
        run: |
          # generate gas reports into the regression folder - if they differ from the ones in the repo, they will be failed in the git-diffs step
          cd ${{ inputs.cwd }}
          uv run yarn gas
        id: gas

      - name: Run upgradeable contract deployment validation
        shell: bash
        run: |
          # check all contracts for deployment upgradeability
          cd ${{ inputs.cwd }}
          uv run yarn validate
        id: validate

      - name: Check for changed repo files
        shell: bash
        run: |
          # if there are any added or changed (excluding staged) files then list them and fail
          cd ${{ inputs.cwd }}
          if ! git diff --quiet || [[ -n "$(git ls-files --others --exclude-standard)" ]]; then
            git status --short
            git diff | head -100
            echo "Git repo has changed, either correctly fix those files locally or .gitignore them"; exit 1;
          fi
        id: git-diffs

      - name: Check some wtf's
        shell: bash
        run: |
          # if the package.json file has a wtf script, run it
          # if it returns anything, print it then fail the action
          cd ${{ inputs.cwd }}
          if jq -e '.scripts.wtf' package.json >/dev/null; then
            out=$(yarn wtf)
            echo "$out"
            if [ -n "$out" ]; then
              echo "wt(actual)f: issues detected by running 'yarn wtf' (which is an optional script in package.json used to detect project bespoke issues)"
              exit 1
            fi
            echo "wtf: no issues detected by running 'yarn wtf' (which is an optional script in package.json used to detect project bespoke issues)"
          fi
          echo "wtf: no script "wtf" in package.json, which is fine and dandy as 'yarn wtf' is an optional script in package.json used to detect project bespoke issues"
          exit 0
        id: wtf
